name: Build AlliedModders extension

on:
  workflow_call:
    inputs:
      sdks:
        description: "Space delimited list of SDKs to build against (e.g., css dods tf2)"
        required: true
        type: string
      artifact-path:
        description: "Artifact path to download from previous jobs"
        default: ""
        type: string

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
        include:
          - os: ubuntu-24.04
            cc: clang-14
            cxx: clang++-14
          - os: windows-2022
            cc: msvc
            cxx: msvc
      fail-fast: false
    name: ${{ matrix.os }} - ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Download artifact
        uses: actions/download-artifact@v4
        if: inputs.artifact-path != ''
        with:
          path: ${{ inputs.artifact-path }}

      - name: Build extension
        uses: srcdslab/action-ambuild@v1
        id: ambuild
        with:
          os: ${{ matrix.os }}
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          ambuild-ref: 'master'
          mm-ref: '1.12-dev'
          sm-ref: 'master'
          hl2sdk-manifests-ref: 'master'
          sdks: ${{ inputs.sdks }}
          configure-path: '../sm-ext-common/configure.py'
          configure-additional-flags: '--enable-optimize --enable-auto-versioning --ext-root "../"'

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.ambuild.outputs.package-path }}
          if-no-files-found: error
          retention-days: 14

  release:
    name: Github release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./gh-artifacts

      - name: Package artifacts
        working-directory: gh-artifacts
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          for platform in *; do
            if [ -d "./$platform/" ]; then
              cd "./$platform/"
              tar -czf "../${{ github.event.repository.name }}-${platform,,}.tar.gz" -T <(ls -1)
              cd -
            fi
          done

      - name: Release packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './gh-artifacts/*.tar.gz'
          tag: ${{ github.ref }}
          file_glob: true
